### ISSUE TITLE
Unable to build charm due to "no such file or directory"

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#640] opened 2022-01-27 20:16 UTC
```
2022-01-27 13:41:38.291 Packing the charm
2022-01-27 13:41:38.292 Running ['charmcraft', 'pack', '--bases-index', '0']
2022-01-27 13:41:38.293 Executing in container: lxc --project charmcraft exec local:charmcraft-knative-activator-23421672-0-0-amd64 --cwd /root -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 charmcraft pack --bases-index 0
2022-01-27 13:41:45.720 :: Packing the charm.                                                             
Building charm in '/root'                                                      
Building charm in '/root' - (2.0s)                                             
Building charm in '/root' \ (2.1s)                                             
Building charm in '/root' | (2.2s)                                             
Building charm in '/root' / (2.3s)                                             
Building charm in '/root' - (2.4s)                                             
Building charm in '/root' \ (2.5s)                                             
Building charm in '/root' | (2.6s)                                             
Building charm in '/root' / (2.7s)                                             
Building charm in '/root' - (2.8s)                                             
Building charm in '/root' \ (2.9s)                                             
Building charm in '/root' | (3.0s)                                             
Building charm in '/root' / (3.1s)                                             
Building charm in '/root' - (3.2s)                                             
Building charm in '/root' \ (3.3s)                                             
Building charm in '/root'                                                      
Parts processing error: Failed to copy '/root/parts/charm/src/.tox/unit/log/unit-0.log': no such file or directory.
2022-01-27 13:41:45.720 :: Full execution log: '/root/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220127-194142.372953.log'
2022-01-27 13:41:46.021 Executing in container: lxc --project charmcraft exec local:charmcraft-knative-activator-23421672-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 test -f /tmp/charmcraft.log
2022-01-27 13:41:46.245 No logs found in instance.
2022-01-27 13:41:46.245 Executing on host: lxc --project charmcraft config device show local:charmcraft-knative-activator-23421672-0-0-amd64
2022-01-27 13:41:46.401 Executing on host: lxc --project charmcraft config device remove local:charmcraft-knative-activator-23421672-0-0-amd64 disk-/root/project
2022-01-27 13:41:46.632 Executing on host: lxc --project charmcraft stop local:charmcraft-knative-activator-23421672-0-0-amd64
2022-01-27 13:41:48.866 Failed to build charm for bases index '0'.
2022-01-27 13:41:48.868 Traceback (most recent call last):
2022-01-27 13:41:48.869   File "/snap/charmcraft/761/lib/charmcraft/commands/build.py", line 467, in pack_charm_in_instance
2022-01-27 13:41:48.869     instance.execute_run(
2022-01-27 13:41:48.869   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxd_instance.py", line 221, in execute_run
2022-01-27 13:41:48.869     return self.lxc.exec(
2022-01-27 13:41:48.869   File "/snap/charmcraft/761/lib/craft_providers/lxd/lxc.py", line 307, in exec
2022-01-27 13:41:48.869     return runner(final_cmd, **kwargs)  # pylint: disable=subprocess-run-check
2022-01-27 13:41:48.869   File "/snap/charmcraft/761/usr/lib/python3.8/subprocess.py", line 516, in run
2022-01-27 13:41:48.869     raise CalledProcessError(retcode, process.args,
2022-01-27 13:41:48.869 subprocess.CalledProcessError: Command '['lxc', '--project', 'charmcraft', 'exec', 'local:charmcraft-knative-activator-23421672-0-0-amd64', '--cwd', '/root', '--', 'env', 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'CHARMCRAFT_MANAGED_MODE=1', 'charmcraft', 'pack', '--bases-index', '0']' returned non-zero exit status 1.
2022-01-27 13:41:48.869 Full execution log: '/home/knkski/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220127-134105.753748.log'
```

This looks like the relevant line:

    Parts processing error: Failed to copy '/root/parts/charm/src/.tox/unit/log/unit-0.log': no such file or directory.

I was able to remove that temp dir from the charm source directory, and delete the lxd container to get the charm building again, and I'll prevent it from happening again with `.jujuignore`. However, I'm unsure why this was breaking things in the first place, as other charms in the bundle were building fine with a `.tox` directory in them.

**Comment by cmatsuoka** [comment] 2022-01-27 20:54
Are you able to reproduce this situation? The problem was first reported in #501, but we didn't find a clear way to reproduce it.

**Comment by facundobatista** [comment] 2022-03-04 20:57
Hello! Any news on this? Thanks!

**Comment by lengau** [comment] 2023-07-13 21:57
@knkski if you manage to redproduce this, please let us know. ITMT I'm going to close this as not reproducible

**Closed by lengau** 2023-07-13 21:57 UTC
Labels: Bug, needs info, parts
