### ISSUE TITLE
`charmcraft info` command

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#404] opened 2021-06-23 19:46 UTC
We need a command that users can execute to get details about a charm. Possibly `charmcraft info <charm-name>`?

Thoughts?

**Comment by jameinel** [comment] 2021-06-23 20:57
There is 'juju info' though it currently needs a running controller to
determine what charm store you are connected to. But I think something like
'charmcraft info' would, indeed, be useful.

**Comment by facundobatista** [comment] 2021-06-24 12:16
Closing this as duplicate of #187, where we took the decision of `juju` providing this functionality, which is also aligned to the behaviours of `snapcraft`/`snap`.

Maybe you could comment in the other bug why the functionality should be duplicated in two different tools, benefits, etc. Thanks!

**Closed by facundobatista** 2021-06-24 12:16 UTC
