### ISSUE TITLE
Charmcraft pack cannot run in a CI?

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#388] opened 2021-06-15 20:09 UTC
Hello,

we have a GitHub actions CI to build and deploy our slurm-charms (https://github.com/omnivector-solutions/slurm-charms/blob/CI/.github/workflows/test_build_release_edge.yaml#L60). 

But charmcraft is now crashing when running in github CI. We install it from the snap (latest/stable), and our CI also has python3/pip3 installed. These are the last commands before crashing (`make charms` invoke `charmcraft pack`):

```bash
Run make charms
  make charms
  echo "charm version: $(cat version)"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.5/x64/lib
Executing ['pip3', 'install', '--target=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/build/venv', '--requirement=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/requirements.txt'] failed with return code 1
problems installing dependencies (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-x84lc565)
make: *** [Makefile:32: slurmd] Error 1
Error: Process completed with exit code 2.
```

Can someone help me understand what is going on here?

**Comment by sergiusens** [comment] 2021-06-16 20:15
Charmcraft might need to learn to output the full logs on error if not on an interactive terminal.

I suspect dependencies are missing, most of which will be solved (as in you will be able to declare them) when craft-parts gets fully integrated (timeline https://discourse.charmhub.io/t/the-charmcraft-roadmap/4614).

For now, you can probably install them manually before triggering the build (e.g.; if you require xml, apt install libxml2-dev and gcc)

**Comment by facundobatista** [comment] 2021-06-17 12:50
One way to debug what really happened is to make `charmcraft` run in `--verbose` mode. Can you please try that and show us the output? Thanks!!

**Comment by heitorPB** [comment] 2021-06-17 13:41
Here's the output with the verbose:

```
2021-06-17 13:08:51,160  charmcraft                     DEBUG    Starting charmcraft version 1.0.0
2021-06-17 13:08:51,160  charmcraft.main                DEBUG    Raw pre-parsed sysargs: args={'help': False, 'verbose': True, 'quiet': False, 'project_dir': 'charm-slurmd'} filtered=['pack']
2021-06-17 13:08:51,160  charmcraft.commands            DEBUG    Couldn't find config file /home/runner/work/slurm-charms/slurm-charms/charm-slurmd/charmcraft.yaml
2021-06-17 13:08:51,160  charmcraft.main                DEBUG    General parsed sysargs: command='pack' args=[]
2021-06-17 13:08:51,162  charmcraft.main                DEBUG    Command parsed sysargs: Namespace(entrypoint=None, requirement=None)
2021-06-17 13:08:51,162  charmcraft.commands.pack       DEBUG    working arguments: {'from': PosixPath('/home/runner/work/slurm-charms/slurm-charms/charm-slurmd'), 'entrypoint': PosixPath('/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/src/charm.py'), 'requirement': [PosixPath('/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/requirements.txt')]}
2021-06-17 13:08:51,162  charmcraft.jujuignore          DEBUG    Translated .jujuignore 2 ".git" => ".*/\.git\Z"
2021-06-17 13:08:51,162  charmcraft.jujuignore          DEBUG    Translated .jujuignore 3 ".svn" => ".*/\.svn\Z"
2021-06-17 13:08:51,162  charmcraft.jujuignore          DEBUG    Translated .jujuignore 4 ".hg" => ".*/\.hg\Z"
2021-06-17 13:08:51,162  charmcraft.jujuignore          DEBUG    Translated .jujuignore 5 ".bzr" => ".*/\.bzr\Z"
2021-06-17 13:08:51,163  charmcraft.jujuignore          DEBUG    Translated .jujuignore 6 ".tox" => ".*/\.tox\Z"
2021-06-17 13:08:51,163  charmcraft.jujuignore          DEBUG    Translated .jujuignore 8 "/build/" => "/build\Z"
2021-06-17 13:08:51,163  charmcraft.jujuignore          DEBUG    Translated .jujuignore 9 "/revision" => "/revision\Z"
2021-06-17 13:08:51,163  charmcraft.jujuignore          DEBUG    Translated .jujuignore 11 ".jujuignore" => ".*/\.jujuignore\Z"
2021-06-17 13:08:51,163  charmcraft.commands.build      DEBUG    Building charm in '/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/build'
2021-06-17 13:08:51,164  charmcraft.commands.build      DEBUG    Linking in generic paths
2021-06-17 13:08:51,164  charmcraft.commands.build      DEBUG    Ignoring directory because of rules: 'build'
2021-06-17 13:08:51,165  charmcraft.commands.build      DEBUG    Creating the 'install' hook script pointing to dispatch
2021-06-17 13:08:51,165  charmcraft.commands.build      DEBUG    Creating the 'upgrade-charm' hook script pointing to dispatch
2021-06-17 13:08:51,165  charmcraft.commands.build      DEBUG    Creating the 'start' hook script pointing to dispatch
2021-06-17 13:08:51,165  charmcraft.commands.build      DEBUG    Installing dependencies
2021-06-17 13:08:51,165  charmcraft.commands.build      DEBUG    Running external command ['pip3', 'list']
2021-06-17 13:08:52,247  charmcraft.commands.build      DEBUG    :: Package             Version
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: ------------------- ----------
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: appdirs             1.4.4
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: attrs               19.3.0
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: blinker             1.4
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: certifi             2019.11.28
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: chardet             3.0.4
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: cloud-init          21.1
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: configobj           5.0.6
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: cryptography        2.8
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: humanize            3.4.1
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: idna                2.8
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: importlib-metadata  1.5.0
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: Jinja2              2.10.1
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: jsonpatch           1.22
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: jsonpointer         2.0
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: jsonschema          3.2.0
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: macaroonbakery      1.3.1
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: MarkupSafe          1.1.0
2021-06-17 13:08:52,248  charmcraft.commands.build      DEBUG    :: more-itertools      4.2.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: netifaces           0.10.4
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: oauthlib            3.1.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pip                 20.0.2
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: probert             0.0.18
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: protobuf            3.15.8
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: PyJWT               1.7.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pymacaroons         0.13.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: PyNaCl              1.4.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pyRFC3339           1.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pyrsistent          0.15.5
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pyserial            3.4
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: python-dateutil     2.8.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pytz                2021.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: pyudev              0.21.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: PyYAML              5.3.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: requests            2.22.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: requests-toolbelt   0.9.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: requests-unixsocket 0.2.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: setuptools          45.2.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: six                 1.14.0
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: tabulate            0.8.9
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: urllib3             1.25.8
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: urwid               2.0.1
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: wheel               0.36.2
2021-06-17 13:08:52,249  charmcraft.commands.build      DEBUG    :: zipp                1.0.0
2021-06-17 13:08:52,294  charmcraft.commands.build      DEBUG    Running external command ['pip3', 'install', '--target=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/build/venv', '--requirement=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/requirements.txt']
2021-06-17 13:08:53,241  charmcraft.commands.build      DEBUG    :: Collecting git+https://github.com/omnivector-solutions/slurm-ops-manager.git@0.6.8 (from -r /home/runner/work/slurm-charms/slurm-charms/charm-slurmd/requirements.txt (line 2))
2021-06-17 13:08:53,241  charmcraft.commands.build      DEBUG    ::   Cloning https://github.com/omnivector-solutions/slurm-ops-manager.git (to revision 0.6.8) to /home/runner/snap/charmcraft/common/pip-req-build-zq1j2zdk
2021-06-17 13:08:53,242  charmcraft.commands.build      DEBUG    ::   Running command git clone -q https://github.com/omnivector-solutions/slurm-ops-manager.git /home/runner/snap/charmcraft/common/pip-req-build-zq1j2zdk
2021-06-17 13:08:53,350  charmcraft.commands.build      DEBUG    ::   warning: unable to access '/etc/gitconfig': Permission denied
2021-06-17 13:08:53,361  charmcraft.commands.build      DEBUG    ::   warning: unable to access '/etc/gitconfig': Permission denied
2021-06-17 13:08:53,361  charmcraft.commands.build      DEBUG    ::   fatal: unknown error occurred while reading the configuration files
2021-06-17 13:08:53,362  charmcraft.commands.build      DEBUG    :: ERROR: Command errored out with exit status 128: git clone -q https://github.com/omnivector-solutions/slurm-ops-manager.git /home/runner/snap/charmcraft/common/pip-req-build-zq1j2zdk Check the logs for full command output.
2021-06-17 13:08:53,399  charmcraft.commands.build      ERROR    Executing ['pip3', 'install', '--target=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/build/venv', '--requirement=/home/runner/work/slurm-charms/slurm-charms/charm-slurmd/requirements.txt'] failed with return code 1
2021-06-17 13:08:53,399  charmcraft                     ERROR    problems installing dependencies (full execution logs in /home/runner/snap/charmcraft/common/charmcraft-log-hwbpjo4s)
make: *** [Makefile:36: slurmd] Error 1
```

`charmcraft` uses pip/python from the snap, right? is the same for `git`?

This same command works on my focal machine, i do not have `/etc/gitconfig`.

**Comment by facundobatista** [comment] 2021-06-18 11:50
I think the problem is that the snap is strictly confined. We're moving to a classic snap in the next release, so it should be able to access your `/etc/gitconfig` just fine. You could give it a try with the edge version of charmcraft, but beware that may be somewhat unstable yet.

To move to the edge version, you can do:

```
sudo snap refresh charmcraft --channel=edge --classic
```

To go back to the stable version:

```
sudo snap refresh charmcraft --channel=stable
```

**Comment by heitorPB** [comment] 2021-06-18 19:26
Using the edge channel for the charmcraft classic snap in our CI fixed this issue. Thanks!

**Closed** 2021-06-18 19:26 UTC
