### ISSUE TITLE
charmcraft pack fails trying to include a non-existing charm/src/.tox/

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#501] opened 2021-08-20 14:35 UTC
My worktree does not have an `src/.tox` subfolder. Log attached.

After running pack again, it worked fine.

[charmcraft.log](https://github.com/canonical/charmcraft/files/7022238/charmcraft.log)

**Comment by cmatsuoka** [comment] 2021-08-20 17:51
Thanks for the report. The repetition of `ignore patterns: ['*.charm', 'build', '*.charm', 'build', '*.charm', 'build'. ...]` is also very wrong, and it's not immediately obvious to me how this can happen.

**Comment by cmatsuoka** [comment] 2021-08-20 21:40
Do you have any information on how I can reproduce this behavior? Did you execute anything unusual, like more than one instance of charmcraft on the same project at the same time, or running tox during the charmcraft execution?

**Comment by sed-i** [comment] 2021-08-25 02:43
I was running only one instance of charmcraft, and I was only using charmcraft pack.
My tox folder was the default (.tox, not src/.tox).
I did not encounter the issue since.

**Comment by cmatsuoka** [comment] 2021-08-31 21:12
Found and fixed the bug causing the `ignore_patterns` anomaly (https://github.com/canonical/craft-parts/pull/120). This fix should be available in the next version of Charmcraft. Still couldn't reproduce the non-existing file bug.

**Comment by sergiusens** [comment] 2021-09-06 16:54
Can you try again with Charmcraft from the edge channel?

**Comment by sed-i** [comment] 2021-09-14 04:26
I can confirm that "ignore_patterns anomaly" is fixed on edge.
Still haven't encountered the non-existing file bug. Feel free to close this.

**Comment by cmatsuoka** [comment] 2021-09-14 11:22
I suspect the `src/.tox` problem is caused by the bug described in issue #514 and, this being the case, should not happen again (but please reopen or create another issue if this assumption is wrong and the bug is not fixed).

**Comment by sed-i** [comment] 2021-10-19 19:38
I enountered this again with charmcraft 1.3.1
[charmcraft131.log](https://github.com/canonical/charmcraft/files/7376211/charmcraft131.log)

**Comment by cmatsuoka** [comment] 2021-10-20 12:55
I'll investigate this to find possible causes. In the meantime, should this happen again, please preserve your `.tox` and `parts` directories so we can reproduce the problem in a controlled environment. (`parts` is inside the build provider if you're not running in destructive mode).

**Comment by erik78se** [comment] 2021-11-23 21:41
Not sure if related, but I get this:

https://discourse.charmhub.io/t/pack-a-hook-based-charm-with-charmcraft/5329/5

**Comment by cmatsuoka** [comment] 2022-03-13 21:03
A similar problem happened in snapcraft: it failed to pull a non-existing directory when creating a snap from a dirty local source. If it's the same bug, it also exists in the original parts lifecycle processing code, instead of being something added in the craft-parts implementation.

**Comment by cmatsuoka** [comment] 2022-03-16 23:20
Snapcraft output showing the problem after modifying a file and repacking an existing snap:
```
$ snapcraft --use-lxd
Launching a container.
/home/claudio/.venv/snapcraft/lib/python3.8/site-packages/pylxd/models/_model.py:146: UserWarning: Attempted to set unknown attribute "project" on instance of "Container"
Waiting for container to be ready
Waiting for network to be ready...
snap "snapd" has no updates available
snap "core20" has no updates available
snap "snapcraft" has no updates available
Skipping pull bash-completion (already ran)
Skipping pull patchelf (already ran)
Skipping pull snapcraft-libs (already ran)
Updating pull step for snapcraft (source changed)
+ snapcraftctl pull
Skipping build bash-completion (already ran)
Skipping build patchelf (already ran)
Skipping build snapcraft-libs (already ran)
Updating build step for snapcraft ('pull' step changed)
Failed to copy '/root/parts/snapcraft/src/test-core22/parts/fail/state/pull': no such file or directory.
Check the path and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

**Comment by facundobatista** [comment] 2022-04-04 14:15
Another case described here: #736

**Comment by amandahla** [comment] 2022-08-31 17:22
I faced a similar problem:
```python
craft_parts.errors.CopyFileNotFound: Failed to copy '/root/parts/charm/src/.git/objects/35/cc257b0cbcbb9421aecf5f9bcf9a417f119ce6': no such file or directory.
```

so I cleaned:
```bash
charmcraft clean
```

Then added ".git" in .jujuignore
```bash
cat .jujuignore 
/venv
*.py[cod]
*.charm
.git
```

Packed again successfully
```bash
charmcraft pack 
Packing the charm                                                                                                                                                     
Created 'checkmk-k8s-operator_ubuntu-20.04-amd64.charm'.                                                                                                              
Charms packed:                                                                                                                                                        
    checkmk-k8s-operator_ubuntu-20.04-amd64.charm  
```

I'm not sure if this is a fix but at least until now, it's working.

**Comment by jameinel** [comment] 2022-09-01 19:55
I ran into something similar when I just created some subdirectories in my
charm (mkdir foo, touch foo/bar). I had to do a 'charmcraft clean' to get
the build to work again.

John
=:->

**Comment by lengau** [comment] 2024-02-22 03:37
Closing this since it's been fixed upstream

**Closed by lengau** 2024-02-22 03:37 UTC
Labels: triaged, parts
