### ISSUE TITLE
Give charmers a mechanism to specify additional files to be included in the build charms.

### ISSUE THREAD

**Issue by gnuoy** [canonical/charmcraft#108] opened 2020-08-06 08:33 UTC
I don't think it is realistic for charmcraft to maintain a static list of files and directories to be included in the charm build process *1. For example the OpenStack charms require the charms readme and copyright notice to be in the built charm. Many charms also have a `files` directory which would also be excluded. It would be useful if there was some mechanism by which a charm author can instruct charmcraft to include additional files or directories in the built charm.

*1 https://github.com/canonical/charmcraft/blob/master/charmcraft/commands/build.py#L38

**Comment by jameinel** [comment] 2020-08-06 09:33
Thanks for opening this. I believe we're tracking this work in #39 

Duplicate of #39

**Comment by jameinel** [comment] 2020-08-06 09:34
Duplicate of #39

**Closed by jameinel** 2020-08-06 09:33 UTC
