### ISSUE TITLE
No version file is generated and it should be

### ISSUE THREAD

**Issue by wallyworld** [canonical/charmcraft#503] opened 2021-08-22 23:09 UTC
When packaging a charm from the root of a VCS checkout (either git or bzr or hg), there needs to be a "version" file generated which contains the relevant sha / revision details. This was done by the "charm build" tool but is missing in craftcraft it seems.

See
https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py#L1336

**Comment by erik78se** [comment] 2021-08-23 10:32
I would actually consider being explicit about generating this file since all these "hidden" features tend to create work which is then null once I discover these easter eggs. 

It might be a question of properly generating output from the "charmcraft build" which tells me that the version file is generated and with what content,

**Comment by erik78se** [comment] 2021-08-23 10:33
Here is a link to a discussion on discourse on this topic: https://discourse.charmhub.io/t/revision-vs-version/5017/2

**Comment by heitorPB** [comment] 2021-08-23 12:59
There is an old issue here about this: https://github.com/canonical/charmcraft/issues/37

**Comment by facundobatista** [comment] 2021-08-23 17:36
Yeap, this is duplicate of #37, please consider adding info there if that report misses any desired functionality, thanks!

**Closed by facundobatista** 2021-08-23 17:36 UTC
