### ISSUE TITLE
charmcraft exiting with 120 exit status and no stdout/stderr

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#608] opened 2021-12-01 20:18 UTC
I have a JavaScript file that looks like this, in the context of wanting to run some `charmcraft` commands in [this action](https://github.com/canonical/charmhub-upload-action):

```javascript
const core = require('@actions/core');
const exec = require('@actions/exec');

(async () => {
    const result = await exec.getExecOutput(
        "/usr/bin/bash",
        ["-c", "/snap/bin/charmcraft --help"],
        {ignoreReturnCode: true}
    );
    core.error(`exit status: ${result.exitCode}`);
    core.error(`stdout: ${result.stdout}`);
    core.error(`stderr: ${result.stderr}`);
})();
```

It's wrapped in a bash call to ensure that I'm not accidentally trying to call a binary that doesn't exist or anything like that. Running that script produces this output:

```
node dist/index.js
[command]/usr/bin/bash -c /snap/bin/charmcraft --help
::error::exit status: 120
::error::stdout:
::error::stderr:
```

It doesn't seem to be an issue with the JavaScript libraries that I'm using, as changing `"/snap/bin/charmcraft --help"` to `"yes --help"` produces this output, as expected:

```
[command]/usr/bin/bash -c yes --help
Usage: yes [STRING]...
  or:  yes OPTION
Repeatedly output a line with all specified STRING(s), or 'y'.

      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/yes>
or available locally via: info '(coreutils) yes invocation'
::error::exit status: 0
::error::stdout: Usage: yes [STRING]...%0A  or:  yes OPTION%0ARepeatedly output a line with all specified STRING(s), or 'y'.%0A%0A      --help     display this help and exit%0A      --version  output version information and exit%0A%0AGNU coreutils
online help: <https://www.gnu.org/software/coreutils/>%0AFull documentation <https://www.gnu.org/software/coreutils/yes>%0Aor available locally via: info '(coreutils) yes invocation'%0A
::error::stderr:
```

The documentation here suggests that it's a problem with the Python interpreter for charmcraft:

https://docs.python.org/3/library/sys.html#sys.exit

> Changed in version 3.6: If an error occurs in the cleanup after the Python interpreter has caught SystemExit (such as an error flushing buffered data in the standard streams), the exit status is changed to 120.

That meshes with me trying to run other charmcraft commands in the same way, which will result in new log files being generated under `~/snap/charmcraft/common/cache/charmcraft/log/` with the expected output, so the command appears to be doing at least some actual work.

**Comment by knkski** [comment] 2021-12-01 22:25
Looks like this is somehow an issue with the way that charmcraft is packaged by snapcraft. Installing charmcraft via pip made everything work as expected.

**Comment by facundobatista** [comment] 2021-12-02 15:02
The problem is that because of [this snapd bug](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753) a classic snap executing another classic snap is unlikely to work.

Closing this as it's not charmcraft related.

**Closed by facundobatista** 2021-12-02 15:02 UTC
