### ISSUE TITLE
charmcraft errors are not printed in requested format

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/charmcraft#825] opened 2022-08-11 03:02 UTC
Charmcraft commands that resulted in error does not output the error in json format even when ``--format json`` flag is used.

Example output:
$ charmcraft upload-resource horizon-k8s openstack-dashboard-image --image $digest --format json
Remote image not found, uploading from local registry.                                                                                       
Wrong status code from server (expected=202, got=408)                                                                                        
Full execution log: '/home/hemanth/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20220810-114949.493003.log'

Charmcraft version: 2.0.0

**Comment by facundobatista** [comment] 2022-08-19 18:50
Hello! Thanks for the report.

The `upload-resource` may produce a json result showing errors when those errors are transmitted from Charmhub, exposing a problem with the uploaded image.

There are countless situations of things that can go wrong during the execution of a command (e.g., network lost) that just make the command to error out showing a message and link to the log. This is not content thought to be captured by a program running charmcraft, that's why it's sent to `stderr` (while json content is sent to `stdout`). The best that the process running charmcraft could do in this case is transmit the error output to the user.

In this particular case the command crashed because the server returned an unexpected code. 408 is a timeout response. Probably all needs to be done is retry the command.

I'm closing this issue as this is the expected behaviour.

Thanks again!

**Closed by facundobatista** 2022-08-19 18:50 UTC
