### ISSUE TITLE
Cant build charm with charmhelpers - missing markupsafe

### ISSUE THREAD

**Issue by erik78se** [canonical/charmcraft#632] opened 2022-01-22 18:10 UTC
I'm trying to build my charm: https://github.com/erik78se/juju-operators-examples/tree/main/metrics-nrpe
branch: nrpe

`charmcraft from snap version 1.4.0 stable`

requirement.txt
```
    ops >= 1.3.0
    psutil==5.9.0
    charmhelpers==0.20.24
```

But I run into this issue which I have no clue on how to resolve.

I'm stuck here.

`charmcraft build -v`

2022-01-22 19:05:01.178 :: 2022-01-22 18:05:01.096 :: 2022-01-22 18:05:00.814    ::     Preparing wheel metadata: started                                    
2022-01-22 19:05:01.182 :: 2022-01-22 18:05:01.178 :: 2022-01-22 18:05:01.096    ::     Preparing wheel metadata: finished with status 'done'                
2022-01-22 19:05:01.444 :: 2022-01-22 18:05:01.181 :: 2022-01-22 18:05:01.177    :: Collecting Jinja2==3.0.3                                                 
2022-01-22 19:05:01.444 :: 2022-01-22 18:05:01.440 :: 2022-01-22 18:05:01.181    ::   Using cached Jinja2-3.0.3.tar.gz (269 kB)                              
2022-01-22 19:05:01.444 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.440    ::     ERROR: Command errored out with exit status 1:                       
2022-01-22 19:05:01.444 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.440    ::      command: /root/parts/charm/build/staging-venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8hz6tk78/Jinja2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8hz6tk78/Jinja2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8hz6tk78/Jinja2/pip-egg-info                                                                                            
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.440    ::          cwd: /tmp/pip-install-8hz6tk78/Jinja2/                          
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.440    ::     Complete output (35 lines):                                          
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.441    ::     Traceback (most recent call last):                                   
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.441 :: 2022-01-22 18:05:01.441    ::       File "<string>", line 1, in <module>                               
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::       File "/tmp/pip-install-8hz6tk78/Jinja2/setup.py", line 4, in <module>                                                                                                                                                            
2022-01-22 19:05:01.445 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::         setup(                                                           
2022-01-22 19:05:01.448 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup                                                                                                               
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::         return distutils.core.setup(**attrs)                             
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::       File "/usr/lib/python3.8/distutils/core.py", line 121, in setup    
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::         dist.parse_config_files()                                        
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/dist.py", line 701, in parse_config_files                                                                                                      
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::         parse_configuration(self, self.command_options,                  
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.442 :: 2022-01-22 18:05:01.441    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration                                                                                                   
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::         meta.parse()                                                     
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse                                                                                                                 
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::         section_parser_method(section_options)                           
2022-01-22 19:05:01.449 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section                                                                                                         
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::         self[name] = value                                               
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__                                                                                                           
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::         value = parser(value)                                            
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version                                                                                                        
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.443 :: 2022-01-22 18:05:01.442    ::         version = self._parse_attr(value, self.package_dir)              
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.442    ::       File "/root/parts/charm/build/staging-venv/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr                                                                                                           
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.442    ::         module = import_module(module_name)                              
2022-01-22 19:05:01.450 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.443    ::       File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                                                                                                      
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.443    ::         return _bootstrap._gcd_import(name[level:], package, level)      
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import    
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap>", line 991, in _find_and_load  
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.444 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                                                                                       
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.445 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap>", line 671, in _load_unlocked  
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.446 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                                                                                                                                          
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.446 :: 2022-01-22 18:05:01.443    ::       File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                                                                     
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.446 :: 2022-01-22 18:05:01.443    ::       File "/tmp/pip-install-8hz6tk78/Jinja2/src/jinja2/__init__.py", line 8, in <module>                                                                                                                                              
2022-01-22 19:05:01.451 :: 2022-01-22 18:05:01.450 :: 2022-01-22 18:05:01.443    ::         from .environment import Environment as Environment              
2022-01-22 19:05:01.452 :: 2022-01-22 18:05:01.450 :: 2022-01-22 18:05:01.443    ::       File "/tmp/pip-install-8hz6tk78/Jinja2/src/jinja2/environment.py", line 15, in <module>                                                                                                                                          
2022-01-22 19:05:01.452 :: 2022-01-22 18:05:01.450 :: 2022-01-22 18:05:01.444    ::         from markupsafe import Markup                                    
2022-01-22 19:05:01.484 :: 2022-01-22 18:05:01.451 :: 2022-01-22 18:05:01.444    ::     ModuleNotFoundError: No module named 'markupsafe'                    
2022-01-22 19:05:01.552 :: 2022-01-22 18:05:01.481 :: 2022-01-22 18:05:01.444    ::     ----------------------------------------                             
2022-01-22 19:05:01.553 :: 2022-01-22 18:05:01.552 :: 2022-01-22 18:05:01.480    :: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                  Traceback (most recent call last):                                                                    
2022-01-22 19:05:01.553 :: 2022-01-22 18:05:01.552 :: File "/snap/charmcraft/x5/lib/charmcra

**UPDATE: If I remove charmhelpers, the build goes through.
#charmhelpers==0.20.24**

Whats the reason for this?

**Comment by erik78se** [comment] 2022-01-22 18:21
charmcraft from snap version 1.4.0 stable

**Comment by EMCP** [comment] 2022-01-22 19:00
I see this @erik78se when python deps are not wired in properly... not in your project but in something you depend on (like Jinja) .. quickest workaround is likely to try pip installing the dependencies

https://github.com/rdickert/project-quicksilver/issues/6#issuecomment-20822097

**Comment by erik78se** [comment] 2022-01-22 19:17
So, basically pull it as part of the install hook? @EMCP

**Comment by cmatsuoka** [comment] 2022-01-22 19:20
Try adding the following to your `charmcraft.yaml`:
```
parts:
  charm:
    charm-python-packages: [setuptools < 58]
```
The reason is that [jinja2 requires a newer setuptools](https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158), but Tempita fails with setuptools 58.0.0 or later because it [removes support for 2to3](https://fedoraproject.org/wiki/Changes/Setuptools_58%2B#Detailed_Description).

**Comment by EMCP** [comment] 2022-01-22 19:21
I just realized.. where this needs to be placed is in the environment where charmcraft runs.. which is inside a snap container if I am not mistaken.. so unfortunately I am unsure how to help you if you cannot pip install into the runtime wherever this charmcraft action is taking place.. if the error is occurring in your hook, then yes.. you'd have to resolve the missing dep yourself.. I have to do this constantly with projects that rely on flask...

**Comment by erik78se** [comment] 2022-01-22 19:24
I'm trying the path of installing as part of the install hook now, but for sure I will also try the @cmatsuoka  suggestion too. What a horrible situation when charmhelpers needs these kind of hacks.

**Comment by erik78se** [comment] 2022-01-22 19:27
I can confirm that it worked @cmatsuoka building the charm with you suggestion.

Where should I place a bug report to get this all fixed?

**Comment by cmatsuoka** [comment] 2022-01-22 19:45
> I can confirm that it worked @cmatsuoka building the charm with you suggestion.
> 
> Where should I place a bug report to get this all fixed?

This situation is caused by setuptools dropping 2to3 support which is used by Tempita, at the same time that jinja2 requires a version of setuptools that's newer than the one available in the archive. Both jinja2 and Tempita are required by charmhelpers, which makes it seem that charmhelpers is causing the problem (but it's not charmhelper's fault).

Charmcraft can't automatically update setuptools in charmcraft because some package (such as Tempita) could require the default version. This is more a situation of a set of packages requiring specific versions of dependencies than a bug somewhere.

**Comment by facundobatista** [comment] 2022-01-25 13:56
This can be closed, right?

**Comment by cmatsuoka** [comment] 2022-01-27 17:06
> This can be closed, right?

I'll close the issue since we have a solution. Please reopen if necessary.

**Closed by cmatsuoka** 2022-01-27 17:06 UTC

**Comment by afreiberger** [comment] 2022-03-14 17:50
I might make the argument that charmcraft should get a fix to detect this issue and make the suggestion of the workaround as a result of the known failure scenario, or that somehow charmcraft.yaml should have the ability to use overrides from projects like charmhelpers.  While this is not a charmhelpers bug it will affect everyone who's recompiling charms with charmcraft if they are supporting bionic in charmcraft.yaml.
