### ISSUE TITLE
charmcraft 1.4.0: impossible to login to charmhub

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#672] opened 2022-02-14 13:52 UTC
```bash
$ charmcraft login
Opening an authorization web page in your browser.
If it does not open, please open this URL:
 https://api.jujucharms.com/identity/login?did=870565472d077a4ab0c6a67e28ea4f205ffa441ccc3e037ffaa42d0dacf07fa7

Logged in as 'omnivector-solutions'.

$ charmcraft whoami
You are not logged in to Charmhub.

$ snap list | grep charmcraft
charmcraft     1.4.0        761    latest/stable  canonical*  classic
```

Am I missing something here?

**Comment by sergiusens** [comment] 2022-02-16 12:41
A segunda-feira, 14 de fevereiro de 2022 16:28:14 -03 Heitor escreveu:
> There is something very weird going on:
> 
> ```bash
> $ charmcraft login
> Opening an authorization web page in your browser.
> If it does not open, please open this URL:
>  https://api.jujucharms.com/identity/login?did=455ef7f55578958436af31a854d65
> 6a4a649273a7892c0068b705c15b2a5af58
> 
> Logged in as 'omnivector-solutions'.
> 
> $ charmcraft upload --release=edge
> prometheus-node-exporter_ubuntu-20.04-amd64_centos-7-amd64.charm
> Credentials not found. Trying to log in...                                 
>                                                                            
>                                                             Opening an
> authorization web page in your browser. If it does not open, please open
> this URL:
>  https://api.jujucharms.com/identity/login?did=254c1db18fb107f11d179b89d2b52
> 2dea36dd3e4c619ce754ee61e6dc392751c
> 
> Revision 4 of 'prometheus-node-exporter' created
> Revision released to edge
> 
> $ charmcraft whoami
> You are not logged in to Charmhub.
> ```
> 
> It appears that `charmcraft` is not storing the login data after any command
> completes.
> 
> Using charmcraft 1.4.0 from latest/stable

The latest charmcraft from edge has a better message when running on systems 
without a keyring.

**Comment by heitorPB** [comment] 2022-02-16 12:53
I do have a keyring on my systems. But what does it have to do with charmcraft? Is this issue fixed on edge channel? When can we expect a new charmcraft release with this fix?

**Comment by facundobatista** [comment] 2022-02-16 14:07
Hello @heitorPB ! 

In which system are you running this? And how did you install charmcraft? 

Thanks!

**Comment by rbarry82** [comment] 2022-02-16 19:34
Does it work if you [`--export` the auth](https://github.com/canonical/charmcraft/issues/631#issuecomment-1021643473)?

**Comment by facundobatista** [comment] 2022-02-16 20:23
Mmm... so strange, the keyring should be found.

Would you please run this and pass the logs? Thanks!

```
charmcraft login --trace
```

Thanks!

**Comment by heitorPB** [comment] 2022-02-17 13:48
> Does it work if you [`--export` the auth](https://github.com/canonical/charmcraft/issues/631#issuecomment-1021643473)?

It works if I export and set the env var. But doesn't feel like a proper solution... If charmcraft can't find a keyring, it shouldn't try to use one, instead should use the old auth method.

**Comment by jamesbeedy** [comment] 2022-02-21 15:54
@heitorPB @facundobatista Do we know of a timeframe for a bug fix release with a fix that addresses this issue?

**Comment by facundobatista** [comment] 2022-02-22 12:02
Charmcraft is not finding a suitable keyring in your system, so it's fallbacking to a MemoryRing, which actually does not really store anything (it was a bug that it did that silently, it's already fixed and louder).

In any way, the real problem is why a keyring is not found. For further analysis, I'd need for you to issue the following commands and show results, please:

```
lsb_release -a
uname -a
echo $DESKTOP_SESSION
echo $XDG_CURRENT_DESKTOP
```

Thanks!

**Comment by heitorPB** [comment] 2022-02-22 15:35
On Tue, 22 Feb 2022 04:02:22 -0800
Facundo Batista ***@***.***> wrote:

> Charmcraft is not finding a suitable keyring in your system, so it's
> fallbacking to a MemoryRing, which actually does not really store
> anything (it was a bug that it did that silently, it's already fixed
> and louder).

Aah, got it. Is there any plan to release a fixed Charmcraft soon?

> In any way, the real problem is why a keyring is not found.

This is my current setup: a remote server running Ubuntu 20.04 Server
LTS, headless, with all Juju-related stuff.

My keyring is on my laptop, and keys are forwarded via SSH to the
software that needs it.

> For
> further analysis, I'd need for you to issue the following commands
> and show results, please:
> 
> ```
> lsb_release -a
> uname -a
> echo $DESKTOP_SESSION
> echo $XDG_CURRENT_DESKTOP
> ```

Here it is:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$ uname -a
Linux valkyrien 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29
UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ echo $DESKTOP_SESSION


$ echo $XDG_CURRENT_DESKTOP

```

**Comment by facundobatista** [comment] 2022-02-22 17:17
> I do have a keyring on my systems. But what does it have to do with charmcraft? Is this issue fixed on edge channel? When can we expect a new charmcraft release with this fix?

You do NOT have a keyring in the remote system. Charmcraft needs it to save the credentials in a safe manner. There is no issue to fix, this is the intended behaviour.

**Comment by sergiusens** [comment] 2022-02-23 10:07
@heitorPB this can help you https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems

**Comment by facundobatista** [comment] 2022-02-25 21:37
Closing, then. Thanks!

**Closed by facundobatista** 2022-02-25 21:37 UTC
