### ISSUE TITLE
`charmcraft login` auto opens the wrong browser

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#692] opened 2022-02-25 21:56 UTC
In Ubuntu 21.10, my default Firefox is the one from snap, but when I `charmcraft login`, it automatically opens up the firefox from apt.

**Comment by facundobatista** [comment] 2022-03-04 15:11
I'm investigating this. I have a similar behaviour (it opens Chrome, while it should open Firefox). It's a problem because of the snap, not charmcraft per se,  but anyway I'm trying to find out why.

**Comment by facundobatista** [comment] 2022-03-08 16:30
The one opening the browser is the authentication library. It uses `webbroser.open` for that, which is a Python's stdlib module. Among other things (it has an extensive multi-platform support) it uses the XDG apps to find out the better browser (`xdg-settings`, which in turn uses `xdg-mime`).

It boils down to what is defined for `text/html` in your system. In mine, KDE, `xdg-mime` uses `ktraderclient5`, and it ends up doing `ktraderclient5 --mimetype text/html --servicetype Application`. In my host the first offer (because it offers a list of apps) is Firefox (with Chromium coming second), but in the charmcraft's snap it offers Chromium (with Firefox coming third). Strangely, from inside other snaps, the behaviour is similar to the host's.

I couldn't find what configuration glitch is making it behave differently, so I took another approach: I explicitly expressed in my system that I wanted Firefox to handle `text/html`. I did this by creating the `$HOME/.local/share/applications/mimeapps.list` file with the following content:

```
[Default Applications]
text/html=firefox.desktop;
```

May you please try this and check if it improves your situation? Thanks!

**Comment by sed-i** [comment] 2022-03-10 20:13
That did not work for me even after logging out and back in.
This is a minor issue though :)

**Comment by facundobatista** [comment] 2022-03-14 14:06
I'm reading [in this documentation about XDG](https://wiki.archlinux.org/title/XDG_MIME_Applications) that the file I indicated above is deprecated, the user overrides should go in `~/.config/mimeapps.list`.

Maybe you can control which firefox is opened there.

That said, can you try opening a Python interpreter and doing the following:

```
import webbrowser
webbrowser.open("https://canonical.com", new=1)
```

If it opens a different browser than Charmcraft, we may have a glitch in the snap and we would need to investigate it. If it opens the same browser than Charmcraft, then we can close this issue as what would need to be improved is the system configuration.

So, please tell us what happened with this test.

Thanks for the info!

**Comment by lengau** [comment] 2024-09-20 19:48
I can no longer reproduce this. The `webbrowser` module is consistently using the browser in my `$BROWSER` env var, followed by the one in `/etc/alternatives`. I think this was something snapd fixed.

**Closed by lengau** 2024-09-20 19:48 UTC
