### ISSUE TITLE
`charmcraft pack` fails running `apt update`

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#511] opened 2021-08-27 14:25 UTC
Running charmcraft pack is resulting in this error https://paste.ubuntu.com/p/7zDF7XHjGF/

This just started happening the other day. I haven't seen it before yesterday in a demo :)

**Comment by sergiusens** [comment] 2021-09-06 16:46
We should create a discourse post about this, as the root cause seems like an identified issue but out of scope of what Charmcraft can do. We will also see if the LXD team can help out with this.

**Comment by facundobatista** [comment] 2021-09-24 18:22
I created a [post in our forum](https://discourse.charmhub.io/t/charmcraft-failing-to-pack-because-of-apt-update-failure/5139) for this, but the real source of solutions is this [post in the Linux Containers forum](https://discuss.linuxcontainers.org/t/lxd-4-12-container-networking-failure-with-docker/10487).

**Closed by facundobatista** 2021-09-24 18:22 UTC
Labels: triaged

**Comment by ca-scribner** [comment] 2022-02-09 14:24
@facundobatista is there some check/error messaging `charmcraft` can do here to give better instruction to the user?  Agreed that the cause is out of the hands of charmcraft, but it amounts to an known-but-unhandled exception and that feels like a UX miss for charmcraft.  Something that pointed to your discourse post would be helpful
