### ISSUE TITLE
`charmcraft pack` should clearly error our alerting users when it fails due to missing internet connectivity

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charmcraft#902] opened 2022-10-11 17:32 UTC
If a lxd container does not have internet connectivity, it will fail with misleading messages like:
```
2022-10-11 10:29:15.766 * Command that failed: 'lxc --project default exec local:charmcraft-kserve-web-app-13668482-0-0-amd64 -- env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin CHARMCRAFT_MANAGED_MODE=1 apt-get install -y apt-utils curl'
2022-10-11 10:29:15.766 * Command exit code: 100
2022-10-11 10:29:15.766 * Command output: b'Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage apt-utils is not available, but is referred to by another package.\nThis may mean that the package is missing, has been obsoleted, or\nis only available from another source\nHowever the following packages replace it:\n  apt\n\n'
2022-10-11 10:29:15.766 * Command standard error output: b"E: Package 'apt-utils' has no installation candidate\nE: Unable to locate package curl\n"
2022-10-11 10:29:15.766 Full execution log: '/home/scribs/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20221011-102832.267768.log'
```

It is hard for a user to see this and recognise it correctly as a lack of internet connectivity.  `charmcraft` should catch this and provide a clear error message, or at least have a network connectivity check early in its process to ensure the container has connectivity

**Comment by facundobatista** [comment] 2022-10-11 20:28
Duplicate of #673

**Closed by facundobatista** 2022-10-11 20:28 UTC
