### ISSUE TITLE
Charmcraft doesn't allow to pull non-published operator framework

### ISSUE THREAD

**Issue by dasm** [canonical/charmcraft#555] opened 2021-09-27 20:58 UTC
Latest operator framework release is dated on Apr 21, 2021: `1.2.0`. In the meantime there were updates similar to  https://github.com/canonical/operator/issues/558 where recommended way of fetching those is to add `git+git://github.com/canonical/operator@72fd89cb92750a4f1674818bf8d10d43e9f85f5e#egg=ops`

It worked on  on Jun 28, but now it stopped working. When using `ops` in `requirements.txt` everything is fine, but it doesn't work with custom git commit due to missing `git` command in lxd container.

```
dasm@test:~/charm-opensearch-k8s$ charmcraft version
1.2.1
```

```
mm 2021-09-27 20:34:52,770  craft_parts.executor.step_handler        DEBUG    :: Running external command ['pip3', '--version']
mm 2021-09-27 20:34:53,322  craft_parts.executor.step_handler        DEBUG    :: :: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
mm 2021-09-27 20:34:53,363  craft_parts.executor.step_handler        DEBUG    :: Running external command ['pip3', 'install', '--target=/root/project/build/parts/charm/install/venv', '--requirement=requirements.txt']
mm 2021-09-27 20:34:54,095  craft_parts.executor.step_handler        DEBUG    :: :: Collecting ops
mm 2021-09-27 20:34:54,096  craft_parts.executor.step_handler        DEBUG    :: ::   Cloning git://github.com/canonical/operator (to revision ae26301b1903719431e849d0d688fee727f9dc81) to /tmp/pip-install-jmwj66jk/ops
mm 2021-09-27 20:34:54,096  craft_parts.executor.step_handler        DEBUG    :: ::   Running command git clone -q git://github.com/canonical/operator /tmp/pip-install-jmwj66jk/ops
mm 2021-09-27 20:34:54,098  craft_parts.executor.step_handler        DEBUG    :: ::   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q git://github.com/canonical/operator /tmp/pip-install-jmwj66jk/ops
mm 2021-09-27 20:34:54,099  craft_parts.executor.step_handler        DEBUG    :: :: ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
mm 2021-09-27 20:34:54,151  craft_parts.executor.step_handler        DEBUG    :: Executing ['pip3', 'install', '--target=/root/project/build/parts/charm/install/venv', '--requirement=requirements.txt'] failed with return code 1
mm 2021-09-27 20:34:54,152  craft_parts.executor.step_handler        DEBUG    :: Traceback (most recent call last):
mm 2021-09-27 20:34:54,152  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x7/lib/charmcraft/charm_builder.py", line 334, in <module>
mm 2021-09-27 20:34:54,152  craft_parts.executor.step_handler        DEBUG    :: main()
mm 2021-09-27 20:34:54,153  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x7/lib/charmcraft/charm_builder.py", line 330, in main
mm 2021-09-27 20:34:54,153  craft_parts.executor.step_handler        DEBUG    :: builder.build_charm()
mm 2021-09-27 20:34:54,153  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x7/lib/charmcraft/charm_builder.py", line 90, in build_charm
mm 2021-09-27 20:34:54,153  craft_parts.executor.step_handler        DEBUG    :: self.handle_dependencies()
mm 2021-09-27 20:34:54,154  craft_parts.executor.step_handler        DEBUG    :: File "/snap/charmcraft/x7/lib/charmcraft/charm_builder.py", line 244, in handle_dependencies
mm 2021-09-27 20:34:54,158  craft_parts.executor.step_handler        DEBUG    :: raise CommandError("problems installing dependencies")
mm 2021-09-27 20:34:54,159  craft_parts.executor.step_handler        DEBUG    :: charmcraft.cmdbase.CommandError: problems installing dependencies
mm 2021-09-27 20:34:54,185  charmcraft                               ERROR    Parts processing error: Failed to run the build script for part 'charm'. (full execution logs in '/tmp/charmcraft.log')
```

**Comment by cmatsuoka** [comment] 2021-09-27 21:16
Duplicate of issue #498. Please verify the issue for details on how to handle this situation.

**Closed by cmatsuoka** 2021-09-27 21:16 UTC

**Comment by dasm** [comment] 2021-09-27 21:18
Hi @cmatsuoka
Would be better to add this information to documentation. Currently, there is no way to find it anywhere.

Thanks for pointing me towards a solution, but I won't be surprised if there will be more similar bug reports.

**Comment by cmatsuoka** [comment] 2021-09-27 21:32
Yes, I believe @facundo is planning to add a small list of useful properties to the existing documentation. (The full list of part properties will be published later after the parts support stabilizes.)

**Comment by facundobatista** [comment] 2021-10-04 11:28
This is the related forum post: https://discourse.charmhub.io/t/charmcraft-and-parts-using-git-requirements/4986
