### ISSUE TITLE
charmcraft build needs a --verbose option

### ISSUE THREAD

**Issue by axinojolais** [canonical/charmcraft#136] opened 2020-08-24 10:42 UTC
Hi,

Running "charmcraft build" is very opaque and doesn't tell you what it does.
Could we please get a --verbose and/or --debug to have more info as to what it's doing ?

Thanks

**Comment by facundobatista** [comment] 2020-08-24 11:29
Duplicate of #42 .

**Closed by facundobatista** 2020-08-24 11:29 UTC
