### ISSUE TITLE
charmcraft built charms still has pycache / .pyc

### ISSUE THREAD

**Issue by hloeung** [canonical/charmcraft#152] opened 2020-09-06 23:26 UTC
Hi,

I thought it was a bad jujuignore file I had where built charms still had __pycache__/*.pyc files but it looks like that's to do with pip install. In my example, it's a WIP charm - https://code.launchpad.net/~hloeung/charm-k8s-content-cache/+git/charm-k8s-content-cache

The built charm has the following files:

```
venv/ops/lib/__pycache__/__init__.cpython-38.pyc
venv/ops/__pycache__/__init__.cpython-38.pyc
venv/ops/__pycache__/main.cpython-38.pyc
venv/ops/__pycache__/storage.cpython-38.pyc
venv/ops/__pycache__/model.cpython-38.pyc
venv/ops/__pycache__/charm.cpython-38.pyc
venv/ops/__pycache__/testing.cpython-38.pyc
venv/ops/__pycache__/jujuversion.cpython-38.pyc
venv/ops/__pycache__/log.cpython-38.pyc
venv/ops/__pycache__/version.cpython-38.pyc
venv/ops/__pycache__/framework.cpython-38.pyc
...
venv/yaml/__pycache__/__init__.cpython-38.pyc
venv/yaml/__pycache__/dumper.cpython-38.pyc
venv/yaml/__pycache__/emitter.cpython-38.pyc
venv/yaml/__pycache__/constructor.cpython-38.pyc
venv/yaml/__pycache__/nodes.cpython-38.pyc
venv/yaml/__pycache__/resolver.cpython-38.pyc
venv/yaml/__pycache__/parser.cpython-38.pyc
venv/yaml/__pycache__/reader.cpython-38.pyc
venv/yaml/__pycache__/scanner.cpython-38.pyc
venv/yaml/__pycache__/cyaml.cpython-38.pyc
venv/yaml/__pycache__/composer.cpython-38.pyc
venv/yaml/__pycache__/error.cpython-38.pyc
venv/yaml/__pycache__/representer.cpython-38.pyc
venv/yaml/__pycache__/serializer.cpython-38.pyc
venv/yaml/__pycache__/tokens.cpython-38.pyc
venv/yaml/__pycache__/events.cpython-38.pyc
venv/yaml/__pycache__/loader.cpython-38.pyc
```

I wonder if this is just a simple fix calling ``pip3 install`` with ``--no-compile`` (or a similar flag).

**Comment by chipaca** [comment] 2020-09-16 11:37
Is this breaking something for you, or was it merely surprising?

Currently, `venv` is copied exactly as produced by `pip`, like a black box, and the `.jujuignore` rules do not apply to it (and those pyc will be used by the python in the live system to speed up start up time -- as long as the versions match -- so it's not wasted; if those pycs are not there, python will spend some time regenerating them on the live system). We could zip the whole `venv` tree for example and it would be completley opaque.
While it's easy to agree that `.pyc` files could be dropped without this breaking the result of the `pip` run, it's a lot harder to determine whether an arbitrary jujuignore rule would break the pip-produced library tree.

**Comment by hloeung** [comment] 2020-09-17 02:24
It's not breaking anything for me at present, merely surprising that it's still being included.

**Comment by facundobatista** [comment] 2021-01-12 12:14
Closing this is the intended behaviour. Thanks for your time!

**Closed by facundobatista** 2021-01-12 12:14 UTC
Labels: build

**Comment by Hyask** [comment] 2025-08-22 12:05
In a simple k8s charm in 2025, this is doubling the size of the final charm, going from 14M to 7.6M once stripped from `.pyc` files. Has the position not changed, and is this still the intended behavior, considering that there is little chance that the version will match and the files will actually be used?

**Comment by lengau** [comment] 2025-09-03 16:49
I don't see why there would be little chance of the version matching. In most cases the versions should match precisely. The only cases I can think of where they wouldn't are where the charm is being deployed on a different base from where it was built, which should be the exception rather than the rule.

**Comment by Hyask** [comment] 2025-09-24 14:23
I'm certainly not an expert in the `.pyc` caching invalidation strategy, but I would suppose that if a charm was built for Noble on a certain date, and used six months later, the Python interpreter in an up-to-date system will certainly have changed ([see the publishing history](https://launchpad.net/ubuntu/+source/python3.12/+publishinghistory)). I don't know whether the `.pyc` can be re-used or not, but I would expect that the answer likely lies around "it depends".
Also, I wouldn't like to be the one debugging a weird Python issue caused by some kind of mismatch between the `.pyc` and the interpreter using them (`bad magic number error` etc...)
