### ISSUE TITLE
charmcraft-log files in /tmp

### ISSUE THREAD

**Issue by jameinel** [canonical/charmcraft#105] opened 2020-08-04 13:27 UTC
I was looking in '/tmp' and I noticed:
```
$ ls
charmcraft-log-2ym5flsu  charmcraft-log-j4fnixya  charmcraft-log-uksp6zlp
charmcraft-log-3_a70vuh  charmcraft-log-j5jis5ub  charmcraft-log-uxyytzhv
charmcraft-log-3didu38k  charmcraft-log-k5eeys7n  charmcraft-log-vt2rd08o
charmcraft-log-4quh1ckg  charmcraft-log-l2vlihqk  charmcraft-log-w6xxbie_
charmcraft-log-50lp0y6z  charmcraft-log-lw12v3in  charmcraft-log-wo3iad9f
```

This is likely left over from the test suite, not from running charmcraft itself (I have 48 of them).
I'm guessing something in our test suite isn't triggering the correct cleanup.

**Comment by facundobatista** [comment] 2020-08-07 19:09
By design, pytest leaves the latest N temporary directories, in case you want to debug anything there.

That said, there are reports of that mechanism [not working exactly ok](https://github.com/pytest-dev/pytest/issues/543), but it seems it was [fixed recently](https://github.com/pytest-dev/pytest/pull/6944).

I think we're ok with this, we just need to wait future pytest releases. I'd close this issue.

**Comment by chipaca** [comment] 2020-08-13 15:52
every time I run pytest on charmcraft (with both pytest 5.4.1 and pytest 6.0.1) I get three new `charmcraft-log-<hex>` directories.

**Comment by chipaca** [comment] 2020-08-13 15:58
These are not pytest logs! they're charmcraft logs. Pytest logs will be `/tmp/pytest-of-john/pytest-NN/`

**Closed** 2020-08-20 10:11 UTC
