### ISSUE TITLE
charmcraft init fails with KeyError getpwuid()

### ISSUE THREAD

**Issue by erik78se** [canonical/charmcraft#261] opened 2021-03-09 10:16 UTC
I'm trying to do a charmcraft init.

==== Commands ======
sssler@dcv-engineering:~/model-postgresql-client/pc$ charmcraft init 
charmcraft internal error! KeyError: 'getpwuid(): uid not found: 3787' (full execution logs in /home/sssler/snap/charmcraft/common/charmcraft-log-jt7z1kh5)

===== My id =====
sssler@dcv-engineering:~/model-postgresql-client/pc$ id sssler
uid=3787(sssler) gid=1000(sdtt) groups=1000(sdtt),25000(linuxclientadm),50005(hpc_dl_ecpa),2410(techsim),50008(hpc_dl_infa),50009(hpc_dl_yspx),3202(oasadmin),3052(sge),50003(hpcadm),2050(catia),45112(calcapp),50006(hpc_dl_1),50004(hpcroot),5016(smsu),51000(hpc_cloud),50007(hpc_dl_other),4711(g4711),3200(oas),8886(gitbackupadm)

==== Environment =====
snap list
charmcraft         0.8.1+43.g9306d5d     302    latest/edge    canonical✓          -

==== Issue consequence =====
Can't create new charm

**Comment by facundobatista** [comment] 2021-04-26 17:05
Duplicate of #199 .

**Closed by facundobatista** 2021-04-26 17:05 UTC
