### ISSUE TITLE
`pip` fails on certificate validation, installing `ca-certificates` doesn't help

### ISSUE THREAD

**Issue by AurelienLourot** [canonical/charmcraft#658] opened 2022-02-08 10:40 UTC
```
# charmcraft.yaml
type: charm

parts:
  charm:
    after:
      - update-certificates
    charm-python-packages:
      # NOTE(lourot): see
      # * https://github.com/canonical/charmcraft/issues/551
      # * https://github.com/canonical/charmcraft/issues/632
      - setuptools < 58
    build-packages:
      - git

  update-certificates:
    plugin: nil
    build-packages:
      - ca-certificates
    override-build: |
      update-ca-certificates

bases:
  - name: ubuntu
    channel: "20.04"
    architectures:
      - amd64
```

```
# requirements.txt
ops >= 1.2.0
git+https://opendev.org/openstack/charm-ops-openstack#egg=ops_openstack
git+https://opendev.org/openstack/charm-interface-hacluster#egg=interface_hacluster
git+https://opendev.org/openstack/charm-ops-interface-openstack-loadbalancer#egg=interface_openstack_loadbalancer
```

`charmcraft -v build` output/failure (charmcraft 1.4.0):

```
[...]
2022-02-08 11:23:42.770 :: 2022-02-08 10:23:42.769 check if Part('update-certificates'):Step.PULL is dirty
2022-02-08 11:23:42.770 :: 2022-02-08 10:23:42.769 add action charm:Step.PRIME(ActionType.RUN)
2022-02-08 11:23:42.770 :: 2022-02-08 10:23:42.770 part build packages: ['ca-certificates']
2022-02-08 11:23:43.386 :: 2022-02-08 10:23:42.770 Requested build-packages: ['ca-certificates', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'python3-venv', 'python3-wheel']
[...]
2022-02-08 11:23:55.533 :: 2022-02-08 10:23:55.532 execute action update-certificates:Action(part_name='update-certificates', step=Step.BUILD, action_type=ActionType.RUN, reason=None)
2022-02-08 11:23:55.543 :: 2022-02-08 10:23:55.532 remove directory /root/parts/update-certificates/build Updating certificates in /etc/ssl/certs...
2022-02-08 11:23:56.082 :: 0 added, 0 removed; done.
2022-02-08 11:23:56.082 :: Running hooks in /etc/ca-certificates/update.d...
2022-02-08 11:23:56.083 :: done.
[...]
2022-02-08 11:24:20.983 :: 2022-02-08 10:24:20.982 :: 2022-02-08 10:24:20.982    :: Collecting ops_openstack
2022-02-08 11:24:21.539 :: 2022-02-08 10:24:20.983 :: 2022-02-08 10:24:20.982    ::   Cloning https://opendev.org/openstack/charm-ops-openstack to /tmp/pip-install-d0sjqifa/ops-openstack
2022-02-08 11:24:21.557 :: 2022-02-08 10:24:21.538 :: 2022-02-08 10:24:20.982    ::   Running command git clone -q https://opendev.org/openstack/charm-ops-openstack /tmp/pip-install-d0sjqifa/ops-openstack
2022-02-08 11:24:21.609 :: 2022-02-08 10:24:21.557 :: 2022-02-08 10:24:21.537    ::   fatal: unable to access 'https://opendev.org/openstack/charm-ops-openstack/': server certificate verification failed. CAfile: none CRLfile: none
2022-02-08 11:24:21.610 :: 2022-02-08 10:24:21.609 :: 2022-02-08 10:24:21.557    :: ERROR: Command errored out with exit status 128: git clone -q https://opendev.org/openstack/charm-ops-openstack /tmp/pip-install-d0sjqifa/ops-openstack Check the logs for full command output.                  Traceback (most recent call last):
```

* [Full output](https://pastebin.ubuntu.com/p/Gh8jKPnxx6/)
* [Full project](https://review.opendev.org/c/openstack/charm-openstack-loadbalancer/+/828162)

**Comment by cmatsuoka** [comment] 2022-02-08 12:36
This problem seems to be caused by an outdated package database in the base image. You can use the following workaround while we investage the root cause:
```
parts:
  ...
  update-certificates:
    plugin: nil
    override-build: |
      apt update
      apt install -y ca-certificates
      update-ca-certificates
```

**Comment by cmatsuoka** [comment] 2022-04-25 20:45
Has this issue been solved (possibly by updated base images) so the workaround can be removed?

**Comment by freyes** [comment] 2022-07-21 13:32
Hi,

I just gave it a try without the workaround and the issue persist:

```
2022-07-21 13:27:52.526 :: 2022-07-21 13:27:52.520    :: Requirement already up-to-date: ops>=1.5.0 in ./staging-venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.5.0)               
2022-07-21 13:27:52.526 :: 2022-07-21 13:27:52.526    :: Collecting ops_openstack                                                                                                                           
2022-07-21 13:27:52.527 :: 2022-07-21 13:27:52.526    ::   Cloning https://opendev.org/openstack/charm-ops-openstack (to revision master) to /tmp/pip-install-0s6klx07/ops-openstack                        
2022-07-21 13:27:53.432 :: 2022-07-21 13:27:52.526    ::   Running command git clone -q https://opendev.org/openstack/charm-ops-openstack /tmp/pip-install-0s6klx07/ops-openstack                           
2022-07-21 13:27:53.442 :: 2022-07-21 13:27:53.432    ::   fatal: unable to access 'https://opendev.org/openstack/charm-ops-openstack/': server certificate verification failed. CAfile: none CRLfile: none 
2022-07-21 13:27:53.562 :: 2022-07-21 13:27:53.442    :: ERROR: Command errored out with exit status 128: git clone -q https://opendev.org/openstack/charm-ops-openstack /tmp/pip-install-0s6klx07/ops-openstack Check the logs for full command output.
```

**Comment by freyes** [comment] 2022-07-21 13:42
Can this be because once charmcraft caches the base image never gets updated again?, this is in my laptop:

```
$ lxc image list --project charmcraft 
+--------------------------------------------------------------------------+--------------+--------+------------------------------------------------------+--------------+-----------+----------+------------------------------+
|                                  ALIAS                                   | FINGERPRINT  | PUBLIC |                     DESCRIPTION                      | ARCHITECTURE |   TYPE    |   SIZE   |         UPLOAD DATE          |
+--------------------------------------------------------------------------+--------------+--------+------------------------------------------------------+--------------+-----------+----------+------------------------------+
| snapshot-craft-com.ubuntu.cloud-buildd-20.04-charmcraft-buildd-base-v0.0 | 0a7bdece4743 | no     | Ubuntu buildd focal amd64                            | x86_64       | CONTAINER | 459.52MB | Aug 27, 2021 at 7:12pm (UTC) |
+--------------------------------------------------------------------------+--------------+--------+------------------------------------------------------+--------------+-----------+----------+------------------------------+
|                                                                          | 0405ea7046c3 | no     | ubuntu 20.04 LTS amd64 (buildd release) (20210921.1) | x86_64       | CONTAINER | 126.20MB | Sep 22, 2021 at 2:55pm (UTC) |
+--------------------------------------------------------------------------+--------------+--------+------------------------------------------------------+--------------+-----------+----------+------------------------------+
```

**Comment by facundobatista** [comment] 2022-08-01 13:39
Hello! Thanks for reporting and investing time in solving the problem.

Would you please use @cmatsuoka 's workaround, run `charmcraft pack --verbosity=trace` and provide full logs? thanks!

**Comment by freyes** [comment] 2022-08-01 14:22
Hi @facundobatista ,

Should I be using a specific version of charmcraft?, because 1.7.1 doesn't recognize the verbosity argument.

```
$ charmcraft pack --verbosity=trace
Usage: charmcraft [options] command [args]...
Try 'charmcraft pack -h' for help.

Error: unrecognized arguments: --verbosity=trace

$ charmcraft version
1.7.1                                                       
```

**Comment by freyes** [comment] 2022-08-01 23:20
upgraded to 2.0 and here its the requested output - https://paste.ubuntu.com/p/qyb963jtS4/

This is how the build log looks like without Claudio's workaround - https://paste.ubuntu.com/p/7HMzgbzKKq/

**Comment by lengau** [comment] 2024-01-26 16:55
This should be resolved in 2.x since craft-providers updates those packages.

**Closed by lengau** 2024-01-26 16:55 UTC
Labels: needs info
