### ISSUE TITLE
Bash auto-completion?

### ISSUE THREAD

**Issue by AurelienLourot** [canonical/charmcraft#372] opened 2021-06-09 09:56 UTC
I'd like to be able to do this

```
$ ls *.charm
zookeeper-k8s.charm
$ charmcraft upload zoo[TAB][TAB][TAB]  # but for now no auto-completion
```

Is it possible? Thanks!

**Comment by facundobatista** [comment] 2021-06-09 20:23
We want to! This is duplicate of #343 . Thanks!

**Closed by facundobatista** 2021-06-09 20:23 UTC
